
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorada;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int WHEN = 24;
  public static final int STRING_LITERAL = 40;
  public static final int FUNCTION = 10;
  public static final int OPSUM = 30;
  public static final int CHAR_LITERAL = 41;
  public static final int PUT = 2;
  public static final int ELSIF = 20;
  public static final int INTEGER = 34;
  public static final int LPAREN = 7;
  public static final int OUT = 14;
  public static final int FOR = 25;
  public static final int RPAREN = 8;
  public static final int NOT = 32;
  public static final int SEMICOLON = 5;
  public static final int IS = 11;
  public static final int IN = 13;
  public static final int COMMA = 4;
  public static final int GET = 3;
  public static final int BEGIN = 15;
  public static final int OPREL = 29;
  public static final int DOT_DOT = 26;
  public static final int LOOP = 22;
  public static final int EXIT = 23;
  public static final int ASSIGN = 27;
  public static final int IF = 17;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int NUMERIC_LITERAL = 42;
  public static final int RETURN = 12;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int NULL = 36;
  public static final int COLON = 6;
  public static final int ELSE = 19;
  public static final int WHILE = 21;
  public static final int FLOAT = 35;
  public static final int THEN = 18;
  public static final int END = 16;
  public static final int OPLOG = 28;
  public static final int FALSE = 37;
  public static final int OPMULT = 31;
  public static final int PROCEDURE = 9;
  public static final int IDENTIFIER = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUT",
  "GET",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "LPAREN",
  "RPAREN",
  "PROCEDURE",
  "FUNCTION",
  "IS",
  "RETURN",
  "IN",
  "OUT",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "WHILE",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "DOT_DOT",
  "ASSIGN",
  "OPLOG",
  "OPREL",
  "OPSUM",
  "OPMULT",
  "NOT",
  "BOOLEAN",
  "INTEGER",
  "FLOAT",
  "NULL",
  "FALSE",
  "TRUE",
  "IDENTIFIER",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "NUMERIC_LITERAL"
  };
}

